# Generated by Django 5.1.6 on 2025-03-14 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoTrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador_peso_edad', models.FloatField()),
                ('indicador_peso_talla', models.FloatField()),
                ('indicador_talla_edad', models.FloatField()),
                ('imc', models.FloatField()),
                ('dx', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('talla', models.FloatField()),
                ('fecha_valoracion', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.paciente')),
            ],
        ),
    ]
