# Generated by Django 5.1.6 on 2025-03-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0003_usuario_es_administrador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajador',
            old_name='puesto',
            new_name='cargo',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='departamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
