# Generated by Django 5.1.6 on 2025-03-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0004_rename_puesto_trabajador_cargo_trabajador_curp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('JEFE', 'Jefe de Departamento'), ('NUTRIOLOGO', 'Nutriólogo')], default='NUTRIOLOGO', max_length=20),
        ),
    ]
