# Generated by Django 5.1.6 on 2025-03-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0005_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_administrador',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('jefe_departamento', 'Jefe de Departamento'), ('nutriologo', 'Nutriólogo')], default='nutriologo', max_length=20),
        ),
    ]
