# Generated by Django 5.1.6 on 2025-03-26 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0007_seguimientotrabajador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientotrabajador',
            name='indicador_peso_edad',
        ),
        migrations.RemoveField(
            model_name='seguimientotrabajador',
            name='indicador_peso_talla',
        ),
        migrations.RemoveField(
            model_name='seguimientotrabajador',
            name='indicador_talla_edad',
        ),
    ]
