# Generated by Django 5.1.6 on 2025-04-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0008_remove_seguimientotrabajador_indicador_peso_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='circunferencia_abdominal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
