# Generated by Django 5.1.6 on 2025-04-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0011_paciente_fecha_registro_trabajador_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso al CAI'),
        ),
    ]
