# Generated by Django 5.1.6 on 2025-04-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0012_trabajador_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
    ]
