# Generated by Django 5.1.6 on 2025-04-14 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0013_trabajador_edad_trabajador_sexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['nombre'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de la última actualización de datos', verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del trabajador', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cai',
            field=models.CharField(choices=[('ESTEFANÍA CASTAÑEDA NUÑEZ', 'CAI Estefanía Castañeda Núñez'), ('JOSEFINA VICENS', 'CAI Josefina Vicens'), ('JULIETA CAMPOS DE GONZÁLEZ PEDRERO', 'CAI Julieta Campos de González Pedrero'), ('JOSÉ MARÍA PINO SUÁREZ', 'CAI José María Pino Suárez'), ('MARINA CORTAZAR VDA. DE ESCOBAR', 'CAI Marina Cortázar Viuda de Escobar'), ('EVA SÁMANO DE LÓPEZ MATEOS', 'CAI Eva Sámano de López Mateos')], help_text='Centro de Atención Infantil asignado', max_length=100, verbose_name='CAI'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.CharField(help_text='Puesto o cargo del trabajador', max_length=255, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='circunferencia_abdominal',
            field=models.FloatField(blank=True, help_text='Medida de la circunferencia abdominal', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)], verbose_name='Circunferencia abdominal (cm)'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='curp',
            field=models.CharField(blank=True, help_text='Clave Única de Registro de Población', max_length=18, null=True, unique=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='departamento',
            field=models.CharField(blank=True, help_text='Departamento o área de trabajo', max_length=255, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad actual del trabajador', null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='enfermedades_preexistentes',
            field=models.TextField(blank=True, help_text='Listado de enfermedades o condiciones previas', verbose_name='Enfermedades preexistentes'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_ingreso',
            field=models.DateField(help_text='Fecha en que el trabajador ingresó al CAI', verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en que se registró al trabajador', verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='imc',
            field=models.FloatField(editable=False, help_text='Calculado automáticamente al guardar', verbose_name='Índice de Masa Corporal'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del trabajador', max_length=255, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre el trabajador', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='peso',
            field=models.FloatField(help_text='Peso en kilogramos', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)], verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], help_text='Sexo biológico del trabajador', max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='talla',
            field=models.FloatField(help_text='Estatura en centímetros', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='Talla (cm)'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['nombre'], name='nutricion_t_nombre_5bb5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['cai'], name='nutricion_t_cai_7567ca_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['departamento'], name='nutricion_t_departa_c0da62_idx'),
        ),
    ]
