# Generated by Django 5.1.6 on 2025-04-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0016_seguimientotrabajador_circunferencia_abdominal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cai',
            field=models.CharField(blank=True, choices=[('ESTEFANÍA CASTAÑEDA NUÑEZ', 'ESTEFANÍA CASTAÑEDA NUÑEZ'), ('JOSEFINA VICENS', 'JOSEFINA VICENS'), ('JULIETA CAMPOS DE GONZÁLEZ PEDRERO', 'JULIETA CAMPOS DE GONZÁLEZ PEDRERO'), ('JOSÉ MARÍA PINO SUÁREZ', 'JOSÉ MARÍA PINO SUÁREZ'), ('MARINA CORTAZAR VDA. DE ESCOBAR', 'MARINA CORTAZAR VDA. DE ESCOBAR'), ('EVA SÁMANO DE LÓPEZ MATEOS', 'EVA SÁMANO DE LÓPEZ MATEOS')], max_length=100, null=True),
        ),
    ]
