# Generated by Django 5.1.6 on 2025-04-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0017_usuario_cai'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='imc_categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
