# Generated by Django 5.1.6 on 2025-04-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0019_alter_paciente_options_alter_paciente_cai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.FloatField(verbose_name='Edad (años)'),
        ),
    ]
