# Generated by Django 5.1.6 on 2025-04-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0020_alter_paciente_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='edad_detallada_texto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Edad detallada'),
        ),
    ]
