# Generated by Django 5.1.6 on 2025-04-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0021_paciente_edad_detallada_texto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='edad_detallada_texto',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='imc_categoria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría IMC'),
        ),
    ]
