# Generated by Django 5.1.6 on 2025-05-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0022_alter_paciente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientotrimestral',
            name='edad',
            field=models.FloatField(),
        ),
    ]
