# Generated by Django 5.1.6 on 2025-05-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0023_alter_seguimientotrimestral_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientotrimestral',
            name='edad',
            field=models.CharField(max_length=50),
        ),
    ]
