# Generated by Django 5.1.6 on 2025-05-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0024_alter_seguimientotrimestral_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientotrimestral',
            name='indicador_peso_edad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seguimientotrimestral',
            name='indicador_peso_talla',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seguimientotrimestral',
            name='indicador_talla_edad',
            field=models.CharField(max_length=50),
        ),
    ]
