# Generated by Django 5.1.6 on 2025-05-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0025_alter_seguimientotrimestral_indicador_peso_edad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='fecha_ingreso',
        ),
    ]
