# Generated by Django 5.2.1 on 2025-05-26 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0027_paciente_created_by_paciente_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientotrabajador',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_trabajador_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seguimientotrimestral',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_nino_eliminados', to=settings.AUTH_USER_MODEL),
        ),
    ]
