# Generated by Django 5.2.1 on 2025-06-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0028_alter_seguimientotrabajador_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmsPesoEdad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('meses', models.PositiveIntegerField()),
                ('sd_m3', models.FloatField(blank=True, null=True)),
                ('sd_m2', models.FloatField(blank=True, null=True)),
                ('sd_m1', models.FloatField(blank=True, null=True)),
                ('mediana', models.FloatField(blank=True, null=True)),
                ('sd_1', models.FloatField(blank=True, null=True)),
                ('sd_2', models.FloatField(blank=True, null=True)),
                ('sd_3', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tabla OMS Peso para Edad',
                'verbose_name_plural': 'Tablas OMS Peso para Edad',
                'db_table': 'oms_peso_edad',
                'unique_together': {('sexo', 'meses')},
            },
        ),
        migrations.CreateModel(
            name='OmsPesoTalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('talla_cm', models.FloatField()),
                ('sd_m3', models.FloatField(blank=True, null=True)),
                ('sd_m2', models.FloatField(blank=True, null=True)),
                ('sd_m1', models.FloatField(blank=True, null=True)),
                ('mediana', models.FloatField(blank=True, null=True)),
                ('sd_1', models.FloatField(blank=True, null=True)),
                ('sd_2', models.FloatField(blank=True, null=True)),
                ('sd_3', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tabla OMS Peso para Talla',
                'verbose_name_plural': 'Tablas OMS Peso para Talla',
                'db_table': 'oms_peso_talla',
                'unique_together': {('sexo', 'talla_cm')},
            },
        ),
        migrations.CreateModel(
            name='OmsTallaEdad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('meses', models.PositiveIntegerField()),
                ('sd_m3', models.FloatField(blank=True, null=True)),
                ('sd_m2', models.FloatField(blank=True, null=True)),
                ('sd_m1', models.FloatField(blank=True, null=True)),
                ('mediana', models.FloatField(blank=True, null=True)),
                ('sd_1', models.FloatField(blank=True, null=True)),
                ('sd_2', models.FloatField(blank=True, null=True)),
                ('sd_3', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tabla OMS Talla para Edad',
                'verbose_name_plural': 'Tablas OMS Talla para Edad',
                'db_table': 'oms_talla_edad',
                'unique_together': {('sexo', 'meses')},
            },
        ),
    ]
